version: '3.8'

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5001:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
